 ## NUMPY BASICS

In [4]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

Creating array from list

In [2]:
arr_1d = np.array([1,2,3,4])
print("1D array : " ,arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : ",arr_2d)

1D array :  [1 2 3 4]
2D array :  [[1 2 3]
 [4 5 6]]


##ARRYS VS LISTS

In [ ]:
list = [1,2,3]
print("list multiplication ",list *2)

array = np.array([1,2,3])
print("array multiplication ",array * 2)

import time 
start = time.time()
list = [i*2 for i in range(1000000)]
print("\nlist operation time : ",time.time()-start)

start = time.time()
array = np.arange(1000000)
print("\narray operation time : ",time.time()-start)



 list multiplication  [1, 2, 3, 1, 2, 3]
 array multiplication  [2 4 6]

list operation time :  0.10067534446716309

array operation time :  0.006295204162597656


##Creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("\nZEROS ARRAY : \n",zeros)

ones = np.ones((2,3))
print("\n ONES ARRAY : \n",ones)

full = np.full((2,2),6 )
print("\n FULL ARRAY : \n",full)

sequence = np.arange(0,11,3)
print("\n SEQUENCE ARRAY : \n",sequence)

random = np.random.random((3,4))
print("\n random ARRAY : \n",random)


ZEROS ARRAY : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ONES ARRAY : 
 [[1. 1. 1.]
 [1. 1. 1.]]

 FULL ARRAY : 
 [[6 6]
 [6 6]]

 SEQUENCE ARRAY : 
 [0 3 6 9]

 random ARRAY : 
 [[0.24334509 0.41044447 0.09182974 0.44235158]
 [0.7348543  0.88226023 0.02680475 0.48837771]
 [0.76933416 0.30018994 0.9572216  0.45208677]]


VECTORS,MATRIX AND TENSOR

VECTORS PROPERTIES

In [15]:
arr = np.array([[1,2,3],[4,5,6]])

print("shape : ",arr.shape)
print("dimension : ",arr.ndim)
print("Size : ",arr.size)
print("DType : ",arr.dtype)

shape :  (2, 3)
dimension :  2
Size :  6
DType :  int64


ARRAY RESHAPPING

In [21]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11])
print("\nOriginal : \n",arr)

reshaped = arr.reshape((3,4))
print("\nreshaped : \n",reshaped)

flattened = reshaped.flatten()
print("\nflattened : \n",flattened)

raveled = reshaped.ravel()
print("\nreveled : \n",raveled)

transpose = reshaped.T
print("\ntranspose : \n",transpose)



Original : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flattened : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

reveled : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

transpose : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
